AnhNH
khanhdn-edsolabs/edsolabs-fe pull request #124
Opened 2021-09-12 08:09 UTC by nguyenanh1609

2021-09-12 08:12 UTC, nguyenanh1609 commented
![image](https://user-images.githubusercontent.com/81566778/132979106-9ee55ced-74b2-4448-8398-f5ebf1ff768c.png)

2021-09-12 11:18 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/about/index.jsx
> +    const [trangthai, settrangthai] = useState(false)
Dùng tiếng anh đi em :D

2021-09-12 11:18 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/about/index.jsx
> +                    <p className={classes.textAlign}>hiện tại tôi đang làm phần ơ bao mi này cũng là 1:09 AM 9/12/2021, thì tôi sắp rơi vào trang thái bất tỉnh nhân sự trong vài tiếng sắp tới nên chắ
=))) có tí cồn vào code cho sung

2021-09-12 14:04 UTC, DungVietLe commented on Day23/AnhNH/my-app/src/components/about/index.jsx
> +    const [trangthai, settrangthai] = useState(false)
chết cười với cái cách đặt tên của em Ánh :D

2021-09-12 14:31 UTC, nguyenanh1609 commented on Day23/AnhNH/my-app/src/components/about/index.jsx
> +    const [trangthai, settrangthai] = useState(false)
Có tí cồn vào tên biến hơi bí ah ạ

2021-09-13 08:54 UTC, nguyenanh1609 commented
Done

2021-09-13 14:21 UTC, tuyenbq-edsolabs requested changes

2021-09-13 14:21 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/App.js
> +    const urlSearchCity = `https://api.weatherapi.com/v1/search.json?key=08220ea307a24ef483455044210909&q=${valueCity}`
Tách api url và key ra env nhé

2021-09-13 14:21 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/about/index.jsx
> +export default Aboutme;
EOL

2021-09-13 14:21 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/lisstweather/index.jsx
> +            ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][dayOfWeek];
tách phần khai báo mảng riêng nhé
`const arrWeekDays = [...]`
`return .... arrWeekDays[dayOfWeek];`

2021-09-13 14:21 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/lisstweather/todayWeather.jsx
> +export default TodayWeather;
EOL

2021-09-13 14:21 UTC, tuyenbq-edsolabs commented on Day23/AnhNH/my-app/src/components/weatherToday/index.jsx
> +export default WeatherToday;
EOL

2021-09-13 15:22 UTC, nguyenanh1609 commented
em sửa xong rồi ạ

2021-09-13 15:54 UTC, merged