ChienTD
khanhdn-edsolabs/edsolabs-fe pull request #134
Opened 2021-09-12 17:48 UTC by chienomh

2021-09-13 06:32 UTC, chienomh commented
![reactjs](https://user-images.githubusercontent.com/81642308/133034833-9dfa5261-e687-4484-ac1b-efc71c42dbc1.png)

2021-09-13 10:00 UTC, chienomh commented
DONE

2021-09-13 13:53 UTC, tuyenbq-edsolabs requested changes

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/About-me/AboutMe.js
> +  console.log(props);
bỏ console.log em nhé

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/About-me/AboutMe.js
> +            <Box component="h3">Sở thích: Nữ</Box>
Thật thà là tốt =))

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/App.js
> +    console.log("<<", props);
bỏ console.log nhé

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/App.js
> +    console.log("<<data", data);
đây nữa

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/next-3-day/next-3-day.js
> +    props && setDataForecast( props.weatherForecast.forecast.forecastday)
sao không dùng luôn mà lại phải set lại nhỉ :D

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/search/search.js
> +  console.log(api);
bỏ console.log

2021-09-13 13:53 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/environment.js
> +
file này liệu còn dùng không e

2021-09-14 00:12 UTC, chienomh commented on Day23/ChienTD/buoi23/src/next-3-day/next-3-day.js
> +    props && setDataForecast( props.weatherForecast.forecast.forecastday)
em sợ nó không có cái cái props dẫn đến lỗi ạ

2021-09-14 02:02 UTC, merged

2021-09-14 02:04 UTC, tuyenbq-edsolabs commented on Day23/ChienTD/buoi23/src/next-3-day/next-3-day.js
> +    props && setDataForecast( props.weatherForecast.forecast.forecastday)
thì em có thể check props tồn tại hay không, rồi dùng mà, tương tự như bbeen trong useEffect này thôi :D